### ISSUE TITLE
Get Raw Accelerometer and Gyroscope Data at 1kHz

### ISSUE THREAD

**Issue by n2d7** [ZaneL/Teensy-ICM-20948#3]
I would like to see if I can get data at 1kHz for accelerometer and the gyroscope. According to the datasheet, accelerometer and gyroscope can be programmed to have higher data rates than 1kHz. 
So I am not clear on why the maximum frequencies for accelerometer and gyroscope data are limited to 225Hz.  If its possible, would you be able to clarify why it is limited to 225Hz and what can be done to achieve higher data rates. 
Thanks!

**Comment by ZaneL** [comment]
It is my understanding that when using the DMP the frequency is limited to something like 225Hz. Of course with raw data you should be able to do better than that. 

In that case I'd use a more simple library like this one. The code will be much easier to debug if you're just looking for raw values.
https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary

Of course by using the raw data instead of the filtered DMP data, the measurements are going to be more noisy.
